// Do not edit this file manually. This file is automatically generated by the init.sh script.
pub const  ADMIN_PUBKEY:&str = "DC3do9sEdJhasHH8jdcKqgi2YL7hhUubZr9WrLZQCws6" ;  // owner jing
pub const VALIDATOR_PUBKEY: &str = "Dgom6bHzPZ38k4XUaXfNXd3mortt5fMYTUaqJh1uPAHR"; //  // owner zero

pub const QUIT_DEADLINE_DURATION:u64 = 86_400;  // 86,400 seconds

pub const PREMIUM_CVT_PRICE:u64 = 5 * 1_000_000_000;
pub const VERSION: &str = "c5335aa3f";
